spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id:
            client-secret:
            scope: profile, email
            redirect-uri: http://localhost:8080/login/oauth2/code/google